stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get update
  - curl https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda3.sh
  - bash ~/miniconda3.sh -bfp ~/miniconda3
  - conda create env -f envXIA.yml

staging:
  stage: deploy
  script:
  - py.test --nbval-lax
  artifacts:
    paths:
    - public
  only:
  - master