image: continuumio/miniconda3:latest

before_script:
  - conda env create -f envXIA.yml
  - source activate envXIA

test:
  stage: deploy
  script:
  - py.test --nbval
  artifacts:
    paths:
    - public
  only:
  - master
